apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mine-safety
      defaultBucket: sensor-data
      tlsSkipVerify: true
    secureJsonData:
      token: mine-safety-token-2024
    isDefault: true
    editable: true

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: mine_safety
    user: mine_safety
    secureJsonData:
      password: mine_safety_2024
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
