CREATE TABLE IF NOT EXISTS sensors (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sensor_id VARCHAR(64) NOT NULL UNIQUE COMMENT '传感器唯一标识',
    name VARCHAR(128) NOT NULL COMMENT '传感器名称',
    type VARCHAR(32) NOT NULL COMMENT '传感器类型: GAS,DUST,CO,TEMPERATURE,WIND',
    protocol VARCHAR(32) NOT NULL COMMENT '通讯协议: MODBUS_RTU,MODBUS_TCP,OPC_UA,CAN,4G,5G',
    location VARCHAR(256) COMMENT '安装位置: 巷道/工作面',
    coordinates_x DECIMAL(10,6) COMMENT 'X坐标',
    coordinates_y DECIMAL(10,6) COMMENT 'Y坐标',
    coordinates_z DECIMAL(10,6) COMMENT 'Z坐标',
    sampling_interval INT DEFAULT 1 COMMENT '采样间隔(秒)',
    min_value DECIMAL(10,4) COMMENT '测量范围最小值',
    max_value DECIMAL(10,4) COMMENT '测量范围最大值',
    unit VARCHAR(16) COMMENT '单位',
    status TINYINT DEFAULT 1 COMMENT '状态: 0-离线, 1-在线, 2-故障',
    last_online_time DATETIME COMMENT '最后在线时间',
    battery_level TINYINT DEFAULT 100 COMMENT '电量百分比: 0-100',
    signal_strength TINYINT DEFAULT 0 COMMENT '信号强度: 0-100',
    data_upload_delay INT DEFAULT 0 COMMENT '数据上报延迟(ms)',
    offline_timeout_minutes INT DEFAULT 10 COMMENT '离线超时时间(分钟)',
    calibration_cycle_days INT DEFAULT 90 COMMENT '校验周期(天)',
    last_calibration_date DATE COMMENT '最后校验日期',
    next_calibration_date DATE COMMENT '下次校验日期',
    warning_threshold DECIMAL(10,4) COMMENT '预警阈值',
    alarm_threshold DECIMAL(10,4) COMMENT '报警阈值',
    power_off_threshold DECIMAL(10,4) COMMENT '断电阈值',
    zone_code VARCHAR(32) COMMENT '区域编码',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sensor_id (sensor_id),
    INDEX idx_type (type),
    INDEX idx_status (status),
    INDEX idx_zone_code (zone_code),
    INDEX idx_battery_level (battery_level),
    INDEX idx_signal_strength (signal_strength)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器配置表';

CREATE TABLE IF NOT EXISTS sensor_data (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sensor_id VARCHAR(64) NOT NULL COMMENT '传感器ID',
    value DECIMAL(12,4) NOT NULL COMMENT '采集值',
    timestamp DATETIME NOT NULL COMMENT '采集时间',
    location VARCHAR(256) COMMENT '位置',
    quality TINYINT DEFAULT 1 COMMENT '数据质量: 0-异常, 1-正常',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_sensor_id (sensor_id),
    INDEX idx_timestamp (timestamp),
    INDEX idx_quality (quality)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器数据表';

CREATE TABLE IF NOT EXISTS alerts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alert_no VARCHAR(64) NOT NULL UNIQUE COMMENT '报警编号',
    sensor_id VARCHAR(64) NOT NULL COMMENT '传感器ID',
    sensor_name VARCHAR(128) COMMENT '传感器名称',
    sensor_type VARCHAR(32) COMMENT '传感器类型',
    location VARCHAR(256) COMMENT '位置',
    level VARCHAR(16) NOT NULL DEFAULT 'WARNING' COMMENT '报警级别: INFO,WARNING,ALERT,CRITICAL',
    message TEXT COMMENT '报警信息',
    value DECIMAL(12,4) COMMENT '触发值',
    threshold DECIMAL(12,4) COMMENT '阈值',
    status TINYINT DEFAULT 0 COMMENT '状态: 0-待处理, 1-已确认, 2-已处理, 3-已关闭',
    acknowledged_by VARCHAR(64) COMMENT '确认人',
    acknowledged_at DATETIME COMMENT '确认时间',
    resolved_by VARCHAR(64) COMMENT '处理人',
    resolved_at DATETIME COMMENT '处理时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_alert_no (alert_no),
    INDEX idx_sensor_id (sensor_id),
    INDEX idx_level (level),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报警记录表';

CREATE TABLE IF NOT EXISTS alert_rules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sensor_type VARCHAR(32) NOT NULL COMMENT '传感器类型',
    level VARCHAR(16) NOT NULL COMMENT '报警级别',
    condition_type VARCHAR(32) NOT NULL COMMENT '条件类型: ABOVE,BELOW,RANGE,CHANGE_RATE',
    threshold DECIMAL(12,4) NOT NULL COMMENT '阈值',
    duration_seconds INT DEFAULT 0 COMMENT '持续时间(秒)',
    enabled TINYINT DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sensor_type (sensor_type),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报警规则表';

INSERT IGNORE INTO alert_rules (sensor_type, level, condition_type, threshold, duration_seconds, enabled) VALUES
('GAS', 'WARNING', 'ABOVE', 0.8, 0, 1),
('GAS', 'ALERT', 'ABOVE', 1.0, 0, 1),
('GAS', 'CRITICAL', 'ABOVE', 1.5, 0, 1),
('DUST', 'WARNING', 'ABOVE', 200, 0, 1),
('DUST', 'ALERT', 'ABOVE', 500, 0, 1),
('DUST', 'CRITICAL', 'ABOVE', 1000, 0, 1),
('CO', 'WARNING', 'ABOVE', 24, 0, 1),
('CO', 'ALERT', 'ABOVE', 50, 0, 1),
('CO', 'CRITICAL', 'ABOVE', 100, 0, 1),
('TEMPERATURE', 'WARNING', 'ABOVE', 26, 0, 1),
('TEMPERATURE', 'ALERT', 'ABOVE', 30, 0, 1),
('TEMPERATURE', 'CRITICAL', 'ABOVE', 35, 0, 1),
('WIND', 'WARNING', 'BELOW', 0.5, 0, 1),
('WIND', 'ALERT', 'BELOW', 0.3, 0, 1),
('WIND', 'CRITICAL', 'BELOW', 0.2, 0, 1);

CREATE TABLE IF NOT EXISTS threshold_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sensor_type VARCHAR(32) NOT NULL COMMENT '传感器类型',
    warning_threshold DECIMAL(10,4) COMMENT '预警阈值',
    alarm_threshold DECIMAL(10,4) COMMENT '报警阈值',
    power_off_threshold DECIMAL(10,4) COMMENT '断电阈值',
    zone_code VARCHAR(32) COMMENT '区域编码(空表示全矿默认)',
    is_active TINYINT DEFAULT 1 COMMENT '是否生效',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sensor_type (sensor_type),
    INDEX idx_zone_code (zone_code),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='阈值配置表';
